Set WshShell = CreateObject("WScript.Shell")
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
WshShell.SendKeys(chr(&hAF))
While true
Dim oPlayer
Set oPlayer = CreateObject("WMPlayer.OCX")
oPlayer.URL = "https://www.youtube.com/watch?v=xDeQVaoTvJM"
oPlayer.controls.play
While oPlayer.playState <> 1 ' 1 = Stopped
WScript.Sleep 100
Wend
oPlayer.close
Wend
